services:
  registry:
    image: registry:3.0.0-rc.3
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - ./registry-config.yml:/etc/distribution/config.yml:ro
      - ./keys/cert.pem:/etc/distribution/cert.pem:ro
    environment:
      OTEL_TRACES_EXPORTER: none

  regauth:
    profiles: [ regauth ]
    image: localhost/evanebb/regauth:latest
    depends_on:
      - postgres
    ports:
      - "127.0.0.1:8000:8000"
    read_only: true
    volumes:
      - ./keys/cert.pem:/etc/regauth/cert.pem:ro
      - ./keys/key.pem:/etc/regauth/key.pem:ro
    environment:
      REGAUTH_INITIALADMIN_USERNAME: admin
      REGAUTH_INITIALADMIN_PASSWORD: admin
      REGAUTH_LOG_LEVEL: debug
      REGAUTH_DATABASE_HOST: postgres
      REGAUTH_DATABASE_NAME: regauth
      REGAUTH_DATABASE_USER: regauth
      REGAUTH_DATABASE_PASSWORD: Welkom01
      REGAUTH_TOKEN_ISSUER: localhost:8000
      REGAUTH_TOKEN_SERVICE: localhost:5000
      REGAUTH_TOKEN_CERTIFICATE: /etc/regauth/cert.pem
      REGAUTH_TOKEN_KEY: /etc/regauth/key.pem
      REGAUTH_TOKEN_ALG: RS256
      REGAUTH_REGISTRY_HOST: localhost:5000

  postgres:
    image: postgres:17
    command:
      - postgres
      - -c
      - log_statement=all
      - -c
      - log_destination=stderr
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: regauth
      POSTGRES_DB: regauth
      POSTGRES_PASSWORD: Welkom01
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: { }
