version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [ nosniff ]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
auth:
  token:
    realm: http://127.0.0.1:8000/token
    service: localhost:5000
    issuer: localhost:8000
    rootcertbundle: /etc/distribution/cert.pem
