// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"github.com/google/uuid"
)

// AddTeamMemberParams is parameters of addTeamMember operation.
type AddTeamMemberParams struct {
	Name string
}

// ChangeUserPasswordParams is parameters of changeUserPassword operation.
type ChangeUserPasswordParams struct {
	Username string
}

// DeletePersonalAccessTokenParams is parameters of deletePersonalAccessToken operation.
type DeletePersonalAccessTokenParams struct {
	ID uuid.UUID
}

// DeleteRepositoryParams is parameters of deleteRepository operation.
type DeleteRepositoryParams struct {
	Namespace string
	Name      string
}

// DeleteTeamParams is parameters of deleteTeam operation.
type DeleteTeamParams struct {
	Name string
}

// DeleteUserParams is parameters of deleteUser operation.
type DeleteUserParams struct {
	Username string
}

// GetPersonalAccessTokenParams is parameters of getPersonalAccessToken operation.
type GetPersonalAccessTokenParams struct {
	ID uuid.UUID
}

// GetRepositoryParams is parameters of getRepository operation.
type GetRepositoryParams struct {
	Namespace string
	Name      string
}

// GetTeamParams is parameters of getTeam operation.
type GetTeamParams struct {
	Name string
}

// GetUserParams is parameters of getUser operation.
type GetUserParams struct {
	Username string
}

// ListTeamMembersParams is parameters of listTeamMembers operation.
type ListTeamMembersParams struct {
	Name string
}

// RemoveTeamMemberParams is parameters of removeTeamMember operation.
type RemoveTeamMemberParams struct {
	Name     string
	Username string
}
