// Code generated by ogen, DO NOT EDIT.

package oas

// OperationName is the ogen operation name
type OperationName = string

const (
	AddTeamMemberOperation             OperationName = "AddTeamMember"
	ChangeUserPasswordOperation        OperationName = "ChangeUserPassword"
	CreatePersonalAccessTokenOperation OperationName = "CreatePersonalAccessToken"
	CreateRepositoryOperation          OperationName = "CreateRepository"
	CreateTeamOperation                OperationName = "CreateTeam"
	CreateUserOperation                OperationName = "CreateUser"
	DeletePersonalAccessTokenOperation OperationName = "DeletePersonalAccessToken"
	DeleteRepositoryOperation          OperationName = "DeleteRepository"
	DeleteTeamOperation                OperationName = "DeleteTeam"
	DeleteUserOperation                OperationName = "DeleteUser"
	GetPersonalAccessTokenOperation    OperationName = "GetPersonalAccessToken"
	GetRepositoryOperation             OperationName = "GetRepository"
	GetTeamOperation                   OperationName = "GetTeam"
	GetUserOperation                   OperationName = "GetUser"
	ListPersonalAccessTokensOperation  OperationName = "ListPersonalAccessTokens"
	ListRepositoriesOperation          OperationName = "ListRepositories"
	ListTeamMembersOperation           OperationName = "ListTeamMembers"
	ListTeamsOperation                 OperationName = "ListTeams"
	ListUsersOperation                 OperationName = "ListUsers"
	RemoveTeamMemberOperation          OperationName = "RemoveTeamMember"
)
