apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "regauth.fullname" . }}-config
  labels:
    {{- include "regauth.labels" . | nindent 4 }}
data:
  config.yml: |
    log:
      level: "{{ .Values.log.level }}"
      formatter: "{{ .Values.log.formatter }}"
    http:
      addr: ":{{ .Values.service.port }}"
    database:
      host: "{{ .Values.database.host }}"
      name: "{{ .Values.database.name }}"
      port: {{ .Values.database.port }}
    token:
      issuer: "{{ .Values.token.issuer }}"
      service: "{{ .Values.token.service }}"
      certificate: "/etc/regauth/tls/{{ default "tls.crt" .Values.token.certFilename }}"
      key: "/etc/regauth/tls/{{ default "tls.key" .Values.token.certKeyFilename }}"
      alg: "{{ .Values.token.alg }}"
