log:
  level: debug
  format: text

database:
  host: localhost
  name: regauth
  user: regauth
  password: Welkom01

token:
  issuer: localhost:8000
  service: localhost:5000
  certificate: keys/cert.pem
  key: keys/key.pem
  alg: RS256

registry:
  host: localhost:5000
