# Initial admin username/password
# This will only have an effect during the first application startup, and should be removed afterward
initialadmin:
  username: admin
  password: admin

# Logging configuration
log:
  # 'debug', 'info', 'warn' or 'error'. Defaults to 'info'
  level: info
  # 'text' or 'json'. Defaults to 'text'
  formatter: text

# HTTP server configuration
http:
  # The address to listen on in 'host:port' format. Defaults to ':8000'.
  addr: ":8000"
  # Path to the TLS certificate/key file to use for HTTPS. If not specified, the server will listen use HTTP.
  certificate: /path/to/cert.pem
  key: /path/to/key.pem

# Database (PostgreSQL) configuration
database:
  host: localhost
  name: regauth
  user: regauth
  password: password
  # The port that the database listens on. Defaults to '5432'.
  port: 5432

# Token signing configuration, this should match the registry configuration.
token:
  issuer: "Registry authentication server"
  service: "Docker registry"
  certificate: /path/to/certificate.pem
  key: /path/to/key.pem
  alg: RS256
