openapi: 3.1.0
info:
  title: Regauth API
  description: |
    The Regauth API allows you to manage repositories, personal access tokens, teams and users.
    
    # Authentication
    Authentication to the API is done through personal access tokens.
    In order to authenticate, you have to supply your personal access token in the `Authorization` header using the `Bearer` type.
    
    The only exception to this is the `/v1/tokens` endpoint, which also allows you to use basic authentication with a username and password to create a new personal access token.
  version: 0.0.1
tags:
  - name: Repositories
  - name: Personal access tokens
  - name: Teams
  - name: Users
paths:
  /v1/repositories:
    get:
      summary: List repositories
      tags: [ Repositories ]
      responses:
        200:
          description: Successfully listed repositories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/RepositoryResponse"
    post:
      summary: Create repository
      tags: [ Repositories ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RepositoryRequest"
      responses:
        200:
          description: Successfully created repository
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RepositoryResponse"
  /v1/repositories/{namespace}/{name}:
    get:
      summary: Get repository
      tags: [ Repositories ]
      parameters:
        - in: path
          required: true
          name: namespace
          schema:
            type: string
        - in: path
          required: true
          name: name
          schema:
            type: string
      responses:
        200:
          description: Successfully returned repository
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RepositoryResponse"
    delete:
      summary: Delete repository
      tags: [ Repositories ]
      parameters:
        - in: path
          required: true
          name: namespace
          schema:
            type: string
        - in: path
          required: true
          name: name
          schema:
            type: string
      responses:
        204:
          description: Successfully deleted repository
  /v1/repositories/{id}:
    get:
      summary: Get repository
      tags: [ Repositories ]
      parameters:
        - in: path
          required: true
          name: id
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Successfully returned repository
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RepositoryResponse"
    delete:
      summary: Delete repository
      tags: [ Repositories ]
      parameters:
        - in: path
          required: true
          name: id
          schema:
            type: string
            format: uuid
      responses:
        204:
          description: Successfully deleted repository
  /v1/tokens:
    get:
      summary: List personal access tokens
      tags: [ Personal access tokens ]
      responses:
        200:
          description: Successfully listed personal access tokens
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PersonalAccessTokenResponse"
    post:
      summary: Create personal access token
      tags: [ Personal access tokens ]
      security:
        - personalAccessToken: [ ]
        - usernamePassword: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PersonalAccessTokenRequest"
      responses:
        200:
          description: Successfully created personal access token
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PersonalAccessTokenCreationResponse"
  /v1/tokens/{id}:
    get:
      summary: Get personal access token
      tags: [ Repositories ]
      responses:
        200:
          description: Successfully returned personal access token
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PersonalAccessTokenResponse"
    delete:
      summary: Delete personal access token
      tags: [ Personal access tokens ]
      parameters:
        - in: path
          required: true
          name: id
          schema:
            type: string
            format: uuid
      responses:
        204:
          description: Successfully deleted personal access token
  /v1/teams:
    get:
      summary: List teams
      tags: [ Teams ]
      responses:
        200:
          description: Successfully listed teams
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TeamResponse"
    post:
      summary: Create team
      tags: [ Teams ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TeamRequest"
      responses:
        200:
          description: Successfully created team
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TeamResponse"
  /v1/teams/{id}:
    get:
      summary: Get team
      tags: [ Teams ]
      responses:
        200:
          description: Successfully returned team
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TeamResponse"
    delete:
      summary: Delete team
      tags: [ Teams ]
      parameters:
        - in: path
          required: true
          name: id
          schema:
            type: string
            format: uuid
      responses:
        204:
          description: Successfully deleted team
  /v1/teams/{id}/members:
    get:
      summary: List team members
      tags: [ Teams ]
      responses:
        200:
          description: Successfully listed team members
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TeamMemberResponse"
    post:
      summary: Add team member
      tags: [ Teams ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TeamMemberRequest"
      responses:
        200:
          description: Successfully added team member
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TeamMemberResponse"
  /v1/teams/{id}/members/{userId}:
    delete:
      summary: Remove team member
      tags: [ Teams ]
      parameters:
        - in: path
          required: true
          name: id
          schema:
            type: string
            format: uuid
        - in: path
          required: true
          name: userId
          schema:
            type: string
            format: uuid
      responses:
        204:
          description: Successfully removed team member
  /v1/users:
    get:
      summary: List users
      tags: [ Users ]
      responses:
        200:
          description: Successfully listed users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UserResponse"
    post:
      summary: Create user
      tags: [ Users ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserRequest"
      responses:
        200:
          description: Successfully created user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserResponse"
  /v1/users/{id}:
    get:
      summary: Get user
      tags: [ Users ]
      responses:
        200:
          description: Successfully returned user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserResponse"
    delete:
      summary: Delete user
      tags: [ Users ]
      parameters:
        - in: path
          required: true
          name: id
          schema:
            type: string
            format: uuid
      responses:
        204:
          description: Successfully deleted user
  /v1/users/{id}/password:
    post:
      summary: Change password for user
      tags: [ Users ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserPasswordChangeRequest"
      parameters:
        - in: path
          required: true
          name: id
          schema:
            type: string
            format: uuid
      responses:
        204:
          description: Successfully updated password
security:
  - personalAccessToken: [ ]
components:
  securitySchemes:
    personalAccessToken:
      type: http
      scheme: bearer
    usernamePassword:
      type: http
      scheme: basic
  schemas:
    RepositoryRequest:
      type: object
      properties:
        namespace:
          type: string
          example: myuser
        name:
          type: string
          example: myimage
        visibility:
          type: string
          enum: [ "private", "public" ]
    RepositoryResponse:
      allOf:
        - $ref: "#/components/schemas/RepositoryRequest"
        - type: object
          properties:
            id:
              type: string
              format: uuid
    PersonalAccessTokenRequest:
      type: object
      properties:
        description:
          type: string
          example: My personal access token
        permission:
          type: string
          enum: [ "readOnly", "readWrite", "readWriteDelete" ]
        expirationDate:
          type: string
          format: date-time
    PersonalAccessTokenResponse:
      allOf:
        - $ref: "#/components/schemas/PersonalAccessTokenRequest"
        - type: object
          properties:
            id:
              type: string
              format: uuid
    PersonalAccessTokenCreationResponse:
      allOf:
        - $ref: "#/components/schemas/PersonalAccessTokenResponse"
        - type: object
          properties:
            token:
              type: string
              description: The newly generated plain-text token. This needs to be stored by the caller, since it cannot be retrieved afterwards.
              example: "registry_pat_SVV_otfQNmSjo7viDiCrC0AKe6Qa_iFhxXJBZE1vMOByC9nbUtBPsz3r"
    TeamRequest:
      type: object
      properties:
        name:
          type: string
          example: myteam
    TeamResponse:
      allOf:
        - $ref: "#/components/schemas/TeamRequest"
        - type: object
          properties:
            id:
              type: string
              format: uuid
    TeamMemberRequest:
      type: object
      properties:
        username:
          type: string
          example: myuser
        role:
          type: string
          enum: [ "admin", "user" ]
    TeamMemberResponse:
      allOf:
        - $ref: "#/components/schemas/TeamMemberRequest"
        - type: object
          properties:
            userId:
              type: string
              format: uuid
    UserRequest:
      type: object
      properties:
        username:
          type: string
          example: myuser
        role:
          type: string
          enum: [ "admin", "user" ]
    UserResponse:
      allOf:
        - $ref: "#/components/schemas/UserRequest"
        - type: object
          properties:
            id:
              type: string
              format: uuid
    UserPasswordChangeRequest:
      type: object
      properties:
        password:
          type: string
          example: newpassword
