name: Build and test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Build
        run: go build -tags viper_bind_struct -v ./cmd/regauth

#      - name: Test
#        run: go test -race -covermode=atomic -coverprofile=coverage.out ./...
#
#      - name: Upload coverage reports to Codecov
#        uses: codecov/codecov-action@e28ff129e5465c2c0dcc6f003fc735cb6ae0c673 # v4.5.0
#        with:
#          files: coverage.out
#          token: ${{ secrets.CODECOV_TOKEN }}
